### ISSUE TITLE
Calling resnest269 results in RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lucasdavid** [Burf/ResNeSt-Tensorflow2#2]
Hello. Thanks for sharing this repository. It's very useful!
I'm having the weirdest problem though, and I was wondering if you came across something similar and if you could point me out in the right direction?

I'm was able to use the resnest269 model in my own computer just fine, but when I try to initialize it in a remote training server, the following error ensues:

```py
>>> x=tf.keras.Input([None, None, 3])
>>> rs50=resnest.resnest269(input_tensor=x, weights=None)
```
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/lerdl/lucas.david/salient-segmentation/src/core/models/backbones/resnest/resnest.py", line 238, in resnest269
    model = tf.keras.Model(img_input, out)
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 146, in __init__
    self._init_graph_network(inputs, outputs)
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 229, in _init_graph_network
    nodes, nodes_by_depth, layers, _ = _map_graph_network(
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 954, in _map_graph_network
    nodes_in_decreasing_depth, layer_indices = _build_map(outputs)
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1081, in _build_map
    _build_map_helper(output, finished_nodes, nodes_in_progress,
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1109, in _build_map_helper
    _build_map_helper(tensor, finished_nodes, nodes_in_progress,
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1109, in _build_map_helper
    _build_map_helper(tensor, finished_nodes, nodes_in_progress,
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1109, in _build_map_helper
    _build_map_helper(tensor, finished_nodes, nodes_in_progress,
  [Previous line repeated 987 more times]
  File "/prj/lerdl/lucas.david/.local/lib/python3.9/site-packages/keras/engine/functional.py", line 1090, in _build_map_helper
    node = layer._inbound_nodes[node_index]  # pylint: disable=protected-access
RecursionError: maximum recursion depth exceeded
```

#### Config of the training server

2 GPUs K40, gcc/7.4, python/3.9.1 and cudnn/8.2_cuda-11.1

```shell
tensorflow                   2.8.0
tensorflow-addons            0.16.1
tensorflow-datasets          4.4.0
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.23.1
tensorflow-metadata          1.2.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
```

**Comment by Burf** [comment]
As a result of checking, it is a problem caused by different "maximum recursion depth" depending on each Python environment. Enter the code below to solve the problem.

>>> import sys
>>> sys.setrecursionlimit(2000)

**Comment by lucasdavid** [comment]
This did the trick. Thank you very much!
